server:
  port: 8080

spring:
  application:
    name: event-manager

  datasource:
    url: jdbc:postgresql://localhost:5432/event_manager
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yaml

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


app:
  kafka:
    topic: event-changes


logging:
  level:
    root: INFO
    org.springframework.web: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html

jwt:
  secret: "374dea8e4dd662caeef44cc2f9b5dde020ffaaf5f69947519664af0d0809d530"
  expiration: 86400000




